---
title: 'Intro to Network Regression'
author: "Tiernan Cahill"
date: "23/06/2021"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Data and Required Packages
We will again be importing the graph objects to be used in this analysis from the serialized RDS format.

We will also need to load a few packages for this lab:

  - `readxl` for importing Excel data
  - `magrittr` for pipes
  - `igraph` for modelling and visualizing our network
  - `statnet` for additional inferential analysis tools

```{r load, message = FALSE}
library(readxl)
# library(magrittr)
library(igraph)
# library(intergraph)
library(statnet)

# Import helper functions
source("lab4_functions.R")
```

```{r data-import, message=FALSE}
# Import existing graph objects
mention_graph <- readRDS("../data/covid_tweets_mention_graph.RDS")

# Import original dataset
lab <- read_excel("../data/covid_tweets.xlsx") %>% 
  rename_all(~str_replace_all(., "\\s+", "")) # Remove whitespace from variable names
```

```{r graph-gen}
# Use the helper functions to generate additional graphs based on shared
# attributes, to be used as IVs in our correlation / regression models

# acctype.mat <- matrix_gen_acctype(lab)
# gender.mat <- matrix_gen_gender(lab)
htag.mat <- matrix_gen_htag(lab)
interest.mat <- matrix_gen_interests(lab)
# region.mat <- matrix_gen_region(lab)
# verified.mat <- matrix_gen_verified(lab)

# Let's take a look at two of the generated matrices
htag.mat[1:10, 1:10]
interest.mat[1:10, 1:10]

# In order to run a QAP tests, we need all the networks to be in a 
# regular (NOT sparse) adjacency matrix format

mention.mat <- as_adjacency_matrix(mention_graph, attr = "weight", sparse = F)
htag.mat <- as.matrix(htag.mat)
interest.mat <- as.matrix(interest.mat)
```

```{r qap-cor}
# Calculate the correlation coefficient between the mention network and shared
# hashtag usage
gcor(mention.mat, htag.mat)

# Run a QAP test to determine if this level of correlation is significant
htag.cor <- qaptest(list(mention.mat, htag.mat),
                    gcor,
                    g1 = 1,
                    g2 = 2,
                    reps = 100)

# View results of QAP test
print(htag.cor)

# Plot results of QAP test
plot(htag.cor, xlim=c(-0.1, 0.1))
```

```{r mrqap-linear}
# Construct a linear multiple regression model using QAP
model.lm <- netlm(mention.mat,
                  list(htag.mat, interest.mat),
                  reps = 10)

# View the model summary
summary(model.lm)
```

```{r mrqap-logit}
# Get an unweighted (binary) matrix representation of the network
mention.mat_bin <- as_adjacency_matrix(mention_graph, attr = NULL, sparse = F)

# Construct a linear multiple regression model using QAP
model.log <- netlogit(mention.mat_bin,
                  list(htag.mat, interest.mat),
                  reps = 10)

# View the model summary
summary(model.log)
```